### ISSUE TITLE
Alternative to HTTP /kinsta-clear-cache/

### ISSUE THREAD

**Issue by mdewyer** [retlehs/kinsta-mu-plugins#5]
Kinsta sites with custom nginx rewrites may not allow access to the /kinsta-clear-cache/ path in the URL, even if accessing through localhost.

Could this endpoint be exposed some other way? Like through a URL that doesn't rely on this specific path? 

Options include:

- Access under the admin (ex: https://domain.com/wp-admin/kinsta-clear-cache/)
- As a request parameter (ex: https://domain.com/?kinsta-clear-cache)
- As code that is referenced (ex: Kinsta/Cache()->kinsta_cache_purge->purge_page())

I realize this is more of a function of the Kinsta system than this specific plugin, since this plugin references what we can't access (https://localhost/kinsta-clear-cache/...) but hoping it may be able to provide / utilize an alternative way that wouldn't conflict with rewrites.

**Comment by JulienMelissas** [comment]
Hey @mdewyer, I'm sure we would all love to see more support from Kinsta on other/better ways to clear the cache, but I think this is more something to bring up with Kinsta. We're just trying to keep the MU plugin up-to-date and installable via composer. Since this is out of scope for what we're trying to do with this repo, I'm going to close this out, but feel free to report back if you make any progress! Cheers.
